#!/usr/bin/perl

##- Nanar <nanardon@mandrake.org>
##-
##- This program is free software; you can redistribute it and/or modify
##- it under the terms of the GNU General Public License as published by
##- the Free Software Foundation; either version 2, or (at your option)
##- any later version.
##-
##- This program is distributed in the hope that it will be useful,
##- but WITHOUT ANY WARRANTY; without even the implied warranty of
##- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##- GNU General Public License for more details.
##-
##- You should have received a copy of the GNU General Public License
##- along with this program; if not, write to the Free Software
##- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# $Id$

use strict;
use Hdlist;
use Getopt::Long;

(@ARGV) or die 
"$0 specfile1.spec [specfile2.spec [...]] 
Give rpms filename produce by a specfile
";

foreach (@ARGV) {
    my $spec = Hdlist::specnew($_);
    my @err = $spec->check();
    if (@err) {
        foreach (Hdlist::print_rpmpb(@err)) {
            print "\t$_\n";
        }
    } else {

    }
}
