#!/usr/bin/perl
 
##- trem <trem@zarb.org>
##-
##- This program is free software; you can redistribute it and/or modify
##- it under the terms of the GNU General Public License as published by
##- the Free Software Foundation; either version 2, or (at your option)
##- any later version.
##-
##- This program is distributed in the hope that it will be useful,
##- but WITHOUT ANY WARRANTY; without even the implied warranty of
##- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##- GNU General Public License for more details.
##-
##- You should have received a copy of the GNU General Public License
##- along with this program; if not, write to the Free Software
##- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# $Id$

use strict;
use Hdlist;

(@ARGV) or die("$0 <rpmfilename>");

foreach (@ARGV) {
  my $header = rpm2header($_);
  if($header) {	
    print "tag\tnom\t\texiste\tvaleur\n";
    foreach ($header->listtag) { 
      print "$_\t" . Hdlist::tagName($_) .  "\t\t";
      my $e;
      $e = $header->hastag("$_");
      print "$e\t";
      eval {
	print $header->tag($_) if($e);
      };
      print "SOUCI: $@" if($@);
      print "\n";
    }
  }
}
